mkcloud: add support for hacloud
use it via
  export hacloud=1

Quick start quide:
You need at least 7, better 9 (for quorum), nodes.
Set the nodenumber accordingly:
  export nodenumber=10
And set desired minimum number of computenodes:
  export nodenumbercompute=1
This example will lead to the following setup:
 1 2-node data cluster (drbd)
 2 3-node clusters (services, network)
 2 compute nodes (unused node is used as compute node)

diff --git a/scripts/mkcloud b/scripts/mkcloud
--- a/scripts/mkcloud
+++ b/scripts/mkcloud
@@ -36,7 +36,11 @@
 #                for ceph testing
 #
 # nodenumber     (default 2)
-#                sets the number of nodes to be created
+#                sets the overall number of nodes to be created
+#
+# nodenumbercompute (default $nodenumber resp. 1 in case of hacloud=1)
+#                set the number of compute nodes in a HA setup, the remaining nodes
+#                of $nodenumber - $nodenumercompute is used as HA cluster nodes
 #
 # vcpus          (default 1)
 #                sets the number of CPU cores assigned to each node (admin and compute)
@@ -49,7 +53,16 @@ net_admin=${net_admin:-192.168.124}
 adminnetmask=${adminnetmask:-255.255.248.0}
 adminip=$net_admin.10
 admingw=$net_admin.1
-nodenumber=${nodenumber:-2}
+nodenumbercomputedefault=2
+[ -n "$hacloud" ] && nodenumbercomputedefault=1
+nodenumber=${nodenumber:-$nodenumbercomputedefault}
+nodenumbercompute=${nodenumbercompute:-$nodenumbercomputedefault}
+[ -n "$hacloud" ] && nodenumberdataclusterdefault=2 # currently only drbd supported with 2 nodes
+nodenumberdatacluster=${nodenumberdatacluster:-$nodenumberdataclusterdefault}
+nodenumbernetworkcluster=${nodenumbernetworkcluster:-''}
+nodenumberservicescluster=${nodenumberservicescluster:-''}
+# '+'-separated list of MACs of the drbd cluster nodes
+drbdnodemacs=${drbdnodemacs:-''}
 cephvolumenumber=${cephvolumenumber:-0}
 allnodeids=`seq 1 $nodenumber`
 vcpus=${vcpus:-1}
@@ -134,6 +147,7 @@ function sshrun()
 {
   ssh root@$adminip "
     export debug=$debug ;
+    export drbdnodemacs=$drbdnodemacs ;
     export cloudsource=$cloudsource ;
     export hacloud=$hacloud ;
     export libvirt_type=$libvirt_type ;
@@ -141,6 +155,10 @@ function sshrun()
     export net_public=$net_public ;
     export networkingplugin=$networkingplugin ;
     export nodenumber=$nodenumber ;
+    export nodenumbercompute=$nodenumbercompute ;
+    export nodenumbernetworkcluster=$nodenumbernetworkcluster ;
+    export nodenumberservicescluster=$nodenumberservicescluster ;
+    export nodenumberdatacluster=$nodenumberdatacluster ;
     export nosetestparameters=${nosetestparameters} ;
     export cephvolumenumber=$cephvolumenumber ;
     export shell=$shell ;
@@ -200,6 +218,7 @@ function h_create_cloud_lvm()
   adminnode_hdd_size=${adminnode_hdd_size:-15}
   computenode_hdd_size=${computenode_hdd_size:-20}
   cephvolume_hdd_size=${cephvolume_hdd_size:-5}
+  drbd_hdd_size=${drbd_hdd_size:-21}
 
   lvcreate -n admin -L ${adminnode_hdd_size}G $cloudvg
   for i in $allnodeids ; do
@@ -211,6 +230,13 @@ function h_create_cloud_lvm()
       for n in $(echo `seq 1 $cephvolumenumber`) ; do
         lvcreate -n node$i-ceph$n -L ${cephvolume_hdd_size}G $cloudvg
       done
+    done
+  fi
+
+  # create volumes for drbd
+  if [ -n "$hacloud" ] ; then
+    for i in `seq 1 $nodenumberdatacluster`; do
+      lvcreate -n node$i-drbd -L ${drbd_hdd_size=}G $cloudvg
     done
   fi
 }
@@ -513,6 +539,7 @@ function h_create_libvirt_computenode_config()
   nodecounter=$2
   macaddress=$3
   cephvolume="$4"
+  drbdvolume="$5"
   nicmodel=virtio
   [ "$libvirt_type" = "xen" ] && nicmodel=e1000
 
@@ -544,6 +571,7 @@ function h_create_libvirt_computenode_config()
       <boot order='2'/>
     </disk>
     $cephvolume
+    $drbdvolume
     <interface type='network'>
       <mac address='$macaddress'/>
       <source network='$cloud-admin'/>
@@ -602,7 +630,24 @@ function setupcompute()
       done
     fi
 
-    h_create_libvirt_computenode_config /tmp/$cloud-node$i.xml $i $macaddress "$cephvolume"
+    drbdvolume=""
+    if [ -n "$hacloud" ] ; then
+      if [ $i -le $nodenumberdatacluster ] ; then
+        drbddev=vd$(echo $alldevices | cut -d" " -f$c)
+        c=$(($c + 1))
+        drbdvolume="
+    <disk type='block' device='disk'>
+      <serial>$cloud-node$i-drbd</serial>
+      <driver name='qemu' type='raw' cache='unsafe'/>
+      <source dev='/dev/$cloudvg/node$i-drbd'/>
+      <target dev='$drbddev' bus='virtio'/>
+    </disk>"
+        drbdnodemacs="${drbdnodemacs}+${macaddress}"
+        drbdnodemacs="${drbdnodemacs#+}"
+      fi
+    fi
+
+    h_create_libvirt_computenode_config /tmp/$cloud-node$i.xml $i $macaddress "$cephvolume" "$drbdvolume"
 
     virsh destroy $cloud-node$i 2>/dev/null
     if ! virsh create /tmp/$cloud-node$i.xml ; then
@@ -611,6 +656,15 @@ function setupcompute()
       exit 74
     fi
   done
+
+  echo "========================================================"
+  echo " Note: If you interrupt mkcloud now and want to proceed"
+  echo "       later, make sure to run the following command:"
+  echo
+  echo " export drbdnodemacs=\"${drbdnodemacs}\""
+  echo
+  echo "========================================================"
+  sleep 10
   return 0
 }
 
@@ -788,7 +842,7 @@ function usage()
   echo
   echo " Optional"
   echo "   hacloud='' | 1  (default='')"
-  echo "       : setup a high availability cloud, requires at least 6 nodes"
+  echo "       : setup a high availability cloud, requires at least 7 (better 9) nodes"
   echo "   TESTHEAD='' | 1  (default='')"
   echo "       : use latest published packages from Devel:Cloud"
   echo "   cephvolumenumber  (default=0)"
@@ -796,6 +850,9 @@ function usage()
   echo "         note: proposal step does NOT contain a ceph proposal, do it manually"
   echo "   nodenumber=2    (default 2)"
   echo "       : set the number of nodes to be created (excl. admin node)"
+  echo '   nodenumbercompute=1  (default $nodenumber resp. 1 in case of hacloud=1)'
+  echo "       :  set the number of compute nodes in a HA setup, the remaining nodes"
+  echo '          of $nodenumber - $nodenumercompute are used as HA cluster nodes'
   echo "   vcpus=1         (default 1)"
   echo "       : set the number of CPU cores per node (admin and compute)"
   echo
@@ -858,11 +915,54 @@ function sanity_checks()
   fi
 
   if [ -n "$hacloud" ] ; then
-    if (( $nodenumber < 6 )) ; then
-      echo "Error: A HA cloud setup requires at least 6 nodes, you configured only: $nodenumber"
-      echo "Please raise the number of nodes via e.g. export nodenumber=6"
-      exit 1
+    local nodenumbercomputeoffset=0
+    if [ -z "$nodenumbernetworkcluster" ] || [ -z "$nodenumberservicescluster" ] || [ -z "$nodenumberdatacluster" ] ; then
+      # currently only drbd with 2 nodes supported
+      nodenumberdatacluster=2
+      local maxnodes=$(( $nodenumber - $nodenumbercompute - $nodenumberdatacluster ))
+      local mn=$maxnodes
+      while [ $mn != 0 ] ; do
+        [ $(( $mn % 2 )) = 0 ] && [ $(( $mn % 4 )) != 0 ] && break
+        mn=$(( $mn - 1 ))
+      done
+      nodenumbercomputeoffset=$(( $maxnodes - $mn ))
+      nodenumbernetworkcluster=$(( $mn / 2 ))
+      nodenumberservicescluster=$(( $mn / 2 ))
     fi
+
+    I="    "
+    echo "== HA node number overview =="
+    echo  "configured nodes (min. nodes) : use case"
+    echo                "$I$nodenumber (9) : nodenumber"
+    echo         "$I$nodenumbercompute (1) : nodenumber compute"
+    echo   "$I$nodenumbercomputeoffset (0) : unused nodes added as compute nodes"
+    echo "Resulting HA node numbers:"
+    echo     "$I$nodenumberdatacluster (2) : nodenumber data cluster"
+    echo  "$I$nodenumbernetworkcluster (3) : nodenumber network cluster"
+    echo "$I$nodenumberservicescluster (3) : nodenumber services cluster"
+
+    # sanity check
+    if [[ $(( $nodenumbercompute + $nodenumbercomputeoffset )) < 1  ]] || \
+       [[ $(( $nodenumberservicescluster + $nodenumbernetworkcluster )) < 6 ]] || \
+       [[ $nodenumberdatacluster < $nodenumberdataclusterdefault ]] ; then
+      echo
+      echo "Error: too few nodes for a HA cloud setup"
+      echo "Please redefine the number of nodes:"
+      echo " export nodenumber=<x>         and/or"
+      echo " export nodenumbercompute=<y>"
+      echo
+      echo "Note:"
+      echo " For a quorum a cluster needs to have an odd number of nodes, at least 3."
+      echo " For drbd cluster only 2 nodes are supported currently."
+      echo " So your nodenumber shoud be:"
+      echo "     compute_node_number + 2 (drbd cluster) + 2 * odd_number (cluster)"
+      exit 88
+    fi
+
+    nodenumbercompute=$(( $nodenumbercompute + $nodenumbercomputeoffset ))
+    echo
+    echo "Waiting 20 seconds review time. Press Ctrl-C to cancel this run."
+    sleep 20
   fi
 
   case "$cloudsource" in
